### ISSUE TITLE
Request to Add Paper

### ISSUE THREAD

**Issue by ldkong1205** [Westlake-AI/Awesome-Mixup#1]
Thank you for maintaining this repository, it is very helpful!

I would like to recommend our recent work, LaserMix, a spatial-prior-based mixing approach for 3D scene understanding.
- Paper: LaserMix for Semi-Supervised LiDAR Semantic Segmentation
- Link: https://arxiv.org/abs/2207.00026
- Code: https://github.com/ldkong1205/LaserMix
- Project Page: https://ldkong.com/LaserMix
- Tutorial: https://zhuanlan.zhihu.com/p/528689803

Thanks again!

**Comment by Lupin1998** [comment]
Hi @ldkong1205, thanks for your attention and appreciation of our [Awesome-Mixup](https://github.com/Westlake-AI/Awesome-Mixup).

We have added your new work, [LaserMix](https://arxiv.org/abs/2207.00026), to the list of semi-supervised learning. As we plan to add new lists of mixup methods designed for downstream tasks (according to [Awesome-Mix](https://github.com/ChengtaiCao/Awesome-Mix)), we will also add [LaserMix](https://arxiv.org/abs/2207.00026) to the list of semantic segmentation in future commits. Thanks again for your help!

Have a nice day

**Comment by ldkong1205** [comment]
> Hi @ldkong1205, thanks for your attention and appreciation of our [Awesome-Mixup](https://github.com/Westlake-AI/Awesome-Mixup).
> 
> We have added your new work, [LaserMix](https://arxiv.org/abs/2207.00026), to the list of semi-supervised learning. As we plan to add new lists of mixup methods designed for downstream tasks (according to [Awesome-Mix](https://github.com/ChengtaiCao/Awesome-Mix), we will also add [LaserMix](https://arxiv.org/abs/2207.00026) to the list of semantic segmentation in future commits. Thanks again for your help!
> 
> Have a nice day

Thank you for your help!
