### ISSUE TITLE
 Incorrect Paper Link in Multi-Modal Section

### ISSUE THREAD

**Issue by huzhaozhe00** [Westlake-AI/Awesome-Mixup#2]
Hi,

First of all, I want to express my appreciation for the work you've done with the Awesome-Mixup repository. 

While browsing through the **Multi-Modal** section, I noticed an issue with one of the paper links. The link for the paper "Enhance image classification via inter-class image mixup with diffusion model" currently points to "PowMix: A Versatile Regularizer for Multimodal Sentiment Analysis," which appears to be incorrect.

Here is the correct link for "Enhance image classification via inter-class image mixup with diffusion model":
[[paper]](https://arxiv.org/abs/2403.19600)

**Comment by JinXins** [comment]
Hi, @huzhaozhe00 
Thank you for pointing this out, we've modified it to the correct link.
